require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/schools", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # School. As you add validations to School, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      School.create! valid_attributes
      get schools_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      school = School.create! valid_attributes
      get school_url(school)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_school_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      school = School.create! valid_attributes
      get edit_school_url(school)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new School" do
        expect {
          post schools_url, params: { school: valid_attributes }
        }.to change(School, :count).by(1)
      end

      it "redirects to the created school" do
        post schools_url, params: { school: valid_attributes }
        expect(response).to redirect_to(school_url(School.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new School" do
        expect {
          post schools_url, params: { school: invalid_attributes }
        }.to change(School, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post schools_url, params: { school: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested school" do
        school = School.create! valid_attributes
        patch school_url(school), params: { school: new_attributes }
        school.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the school" do
        school = School.create! valid_attributes
        patch school_url(school), params: { school: new_attributes }
        school.reload
        expect(response).to redirect_to(school_url(school))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        school = School.create! valid_attributes
        patch school_url(school), params: { school: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested school" do
      school = School.create! valid_attributes
      expect {
        delete school_url(school)
      }.to change(School, :count).by(-1)
    end

    it "redirects to the schools list" do
      school = School.create! valid_attributes
      delete school_url(school)
      expect(response).to redirect_to(schools_url)
    end
  end
end
